spring:

  jpa:
    properties:
      hibernate:
        default_schema: public
        hbm2ddl:
          auto: update


  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: HoWsJp6pjjma46g07BDvtN5wq0BdCGYU
            client-secret: CJbY3kkaM775sdAdt_ba6T6CY1423GDxgJ-zCU8AxCbgM8sViedqMB8XjPolOUw3
            scope: openid, profile, email
        provider:
          okta:
            issuer-uri: https://dev-hdgki4zq4n1n4rzb.us.auth0.com/oauth2/default

server:
  ssl:
    enabled: true
    key-store: classpath:mykeystore.p12
    key-store-type: PKCS12
    key-store-password: mypassword

  port: 8443

